#/******************************************************************************
#** PROGRAMME  docker-compose.yml                                             **
#**                                                                           **
#** Lieu      : ETML - section informatique                                   **
#** Auteur    : Joachim Berchel                                               **
#** Date      : 29.05.2024                                                    **
#**                                                                           **
#** Modifications                                                             **
#**   Auteur  :                                                               **
#**   Version :                                                               **
#**   Date    :                                                               **
#**   Raisons :                                                               **
#**                                                                           **
#**                                                                           **
#******************************************************************************/

#/******************************************************************************
#** DESCRIPTION                                                               **
#** Application ASP de jeu de clicker                                         **     
#**                                                                           **
#**                                                                           **
#******************************************************************************/

version: '3.4'


networks:
  db_network: 
    driver: bridge 
    ipam: 
      config:
        - subnet: 192.168.0.0/24 

services:
  fastclieckwebappmvc: 
    image: ${DOCKER_REGISTRY-}fastclieckwebappmvc
    build:
      context: .
      dockerfile: FastClieckWebAppMVC/Dockerfile #Path of the Dockerfile
    networks:
      db_network:
        ipv4_address: 192.168.0.2 # set it's ip address
    depends_on: 
      db: # define the project's dependence on the DB container
        condition: service_healthy #the db container must be switched on to be launched 
  db:
    image: mysql/mysql-server:5.7 
    container_name: mysql1 # Container's name
    environment: # Environment variable for mysql configuration
      MYSQL_ROOT_PASSWORD: root # root's password
      MYSQL_USER: db_user # name of a user
      MYSQL_PASSWORD: db_user_pass # password of a user
    restart: always # automatically restart the application
    ports: # map the ports 
      - "3306:3306"  
    expose: # open the port
      - 3306 
    volumes: # Define the volumes
      - "./data.sql:/tmp/data.sql"
    networks: 
      db_network: # assigns the container to the db_network network
        ipv4_address: 192.168.0.10 # Define his IP address
    command: "--init-file /tmp/data.sql" # Command to initialise the data directory 
    healthcheck: # Check that the container is switched on
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s # Define the interval between each check
      retries: 5 # Number of try