version: '3.4'

#Specify the network
networks:
  db_network: 
    driver: bridge 
    ipam:
      config:
        - subnet: 192.168.0.0/24
 
#container
services:
  #The ASP containerized
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    networks: 
      db_network:
        ipv4_address: 192.168.0.2
    depends_on: 
      db:
        condition: service_healthy
  #The mysql server
  db:
    image: mysql/mysql-server:5.7
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "3306:3306"  
    expose:
      - 3306 
    volumes:
      - "./db.sql:/tmp/db.sql"
    networks: 
      db_network:
        ipv4_address: 192.168.0.10
    command: "--init-file /tmp/db.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5